/** Central query-key factory for the server-state cache. */
export const qk = {
  me: ['me'] as const,
  projects: ['projects'] as const,
  project: (idOrKey: string) => ['project', idOrKey.toUpperCase()] as const,
  board: (projectId: string) => ['board', projectId] as const,
  tasks: (params: Record<string, unknown>) => ['tasks', params] as const,
  allTasks: ['tasks'] as const,
  task: (key: string) => ['task', key.toUpperCase()] as const,
  comments: (taskKey: string) => ['comments', taskKey.toUpperCase()] as const,
  attachments: (taskKey: string) => ['attachments', taskKey.toUpperCase()] as const,
  taskActivity: (taskKey: string) => ['activity', 'task', taskKey.toUpperCase()] as const,
  projectActivity: (projectId: string) => ['activity', 'project', projectId] as const,
  orgActivity: ['activity', 'org'] as const,
  sprints: (projectId: string) => ['sprints', projectId] as const,
  reports: (projectId: string) => ['reports', projectId] as const,
  dashboard: ['dashboard'] as const,
  notifications: ['notifications'] as const,
  members: ['members'] as const,
  users: ['users'] as const,
  teams: ['teams'] as const,
  search: (q: string) => ['search', q] as const,
  labels: ['labels'] as const,
  subtasks: (key: string) => ['subtasks', key.toUpperCase()] as const,
  timeEntries: (key: string) => ['time', 'task', key.toUpperCase()] as const,
  timer: ['timer'] as const,
  timesheet: (params: Record<string, unknown>) => ['time', 'sheet', params] as const,
  goals: ['goals'] as const,
  documents: (projectId?: string) => ['documents', projectId ?? 'all'] as const,
  document: (id: string) => ['document', id] as const,
  automations: (projectId: string) => ['automations', projectId] as const,
  webhooks: ['webhooks'] as const,
  roadmap: (projectId?: string) => ['roadmap', projectId ?? 'all'] as const,
  workflow: (projectId: string) => ['workflow', projectId] as const,
  integrations: ['integrations'] as const,
  emailPrefs: ['email', 'preferences'] as const,
  emailStatus: ['email', 'status'] as const,
  fields: (projectId: string) => ['fields', projectId] as const,
  views: (projectId: string) => ['views', projectId] as const,
  trash: ['trash'] as const,
  workload: (params: Record<string, unknown>) => ['workload', params] as const,
  burndown: (sprintId: string) => ['burndown', sprintId] as const,
  velocity: (projectId: string) => ['velocity', projectId] as const,
  forms: (projectId: string) => ['forms', projectId] as const,
};
